DATA SEGMENT
    X DB 0CDH
    Z DB 0FBH
    DIFF DB ?
    BORROW DB 00H
    DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:
    MOV AX,DATA   
    MOV DS,AX
    MOV AL,X
    SUB AL,Z
    JNB SKIP
    INC BORROW
    SKIP: MOV DIFF,AL
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START